/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author 029181066
 */
public class CadAlunos extends javax.swing.JFrame {

    /**
     * Creates new form CadAlunos
     */
    Classes.Aluno vetor[] = new Classes.Aluno[100];
    
    public CadAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTurno = new javax.swing.ButtonGroup();
        lMatrícula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lTitulo = new javax.swing.JLabel();
        lAluno = new javax.swing.JLabel();
        txtAluno = new javax.swing.JTextField();
        lCurso = new javax.swing.JLabel();
        cbCursos = new javax.swing.JComboBox<>();
        lEndereco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEndereco = new javax.swing.JTextArea();
        lTurno = new javax.swing.JLabel();
        lIdioma = new javax.swing.JLabel();
        btMatutino = new javax.swing.JRadioButton();
        btVespertino = new javax.swing.JRadioButton();
        btNoturno = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        lMensalidade = new javax.swing.JLabel();
        fTxtMensalidade = new javax.swing.JFormattedTextField();
        btCadastrar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        lDesconto = new javax.swing.JLabel();
        fTxtDesconto = new javax.swing.JFormattedTextField();
        cboxBolsista = new javax.swing.JCheckBox();
        lValorFinal = new javax.swing.JLabel();
        fTxtValorFinal = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lMatrícula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lMatrícula.setText("Matrícula:");

        txtMatricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lTitulo.setText("Cadastro de Alunos");

        lAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lAluno.setText("Aluno(a):");

        txtAluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lCurso.setText("Curso:");

        cbCursos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administração", "Análise e Desenvolvimento de Sistemas", "Arquitetura e Urbanismo", "Biomedicina", "Ciências Contábeis", "Ciência da Computação", "Ciências Econômicas", "Comunicação e Marketing", "Comunicação Institucional", "Design", "Design de Interiores", "Design de Moda", "Direito", "Educação Física", "Enfermagem", "Engenharia Ambiental", "Engenharia Civil", "Engenharia de Computação", "Engenharia de Produção", "Engenharia Elétrica", "Engenharia Mecânica", "Engenharia Mecatrônica", "Engenharia de Petróleo", "Engenharia Química", "Estética e Cosmética", "Eventos", "Farmácia", "Fisioterapia", "Gastronomia", "Gestão Ambiental", "Gestão Comercial", "Gestão de Turismo", "Gestão Financeira", "Gestão de Recursos Humanos", "Jornalismo", "Logística", "Marketing", "Medicina", "Medicina Veterinária", "Nutrição", "Pedagogia", "Petróleo e Gás", "Processos Gerenciais", "Produção Multimídia – Mídias Digitais", "Psicologia", "Publicidade e Propaganda", "Redes de Computadores", "Relações Internacionais", "Relações Públicas", "Serviço Social", "Sistemas de Informação", "Sistemas para Internet" }));

        lEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lEndereco.setText("Endereço:");

        txtEndereco.setColumns(20);
        txtEndereco.setRows(5);
        jScrollPane1.setViewportView(txtEndereco);

        lTurno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lTurno.setText("Turno:");

        lIdioma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lIdioma.setText("Idioma(s):");

        btTurno.add(btMatutino);
        btMatutino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btMatutino.setText("Matutino");

        btTurno.add(btVespertino);
        btVespertino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btVespertino.setText("Vespertino");

        btTurno.add(btNoturno);
        btNoturno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btNoturno.setText("Noturno");

        jLista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Alemão", "Espanhol", "Francês", "Inglês", "Português" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jLista);

        lMensalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lMensalidade.setText("Mensalidade:");

        fTxtMensalidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        fTxtMensalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fTxtMensalidadeFocusLost(evt);
            }
        });
        fTxtMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTxtMensalidadeActionPerformed(evt);
            }
        });

        btCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        lDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lDesconto.setText("Desconto:");

        fTxtDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        fTxtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fTxtDescontoFocusLost(evt);
            }
        });

        cboxBolsista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboxBolsista.setText("Bolsista");
        cboxBolsista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxBolsistaActionPerformed(evt);
            }
        });

        lValorFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lValorFinal.setText("Valor Final:");

        fTxtValorFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lAluno)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(lTitulo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAluno))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lMatrícula)
                                            .addComponent(lCurso)
                                            .addComponent(lTurno))
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lEndereco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCursos, 0, 302, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btMatutino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btVespertino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btNoturno)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lIdioma)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxBolsista)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lMensalidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lValorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fTxtMensalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(fTxtValorFinal))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lDesconto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fTxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lTitulo)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAluno)
                    .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMatrícula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCurso)
                    .addComponent(cbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTurno)
                            .addComponent(btMatutino)
                            .addComponent(btVespertino)
                            .addComponent(btNoturno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lIdioma)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lEndereco))
                .addGap(12, 12, 12)
                .addComponent(cboxBolsista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMensalidade)
                    .addComponent(fTxtMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDesconto)
                    .addComponent(fTxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lValorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fTxtValorFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        
        Classes.Aluno a1;
        a1 = new Classes.Aluno(Integer.parseInt(txtMatricula.getText()));
        a1 = new Classes.Aluno(Integer.parseInt(txtAluno.getText()));
        
        addAluno(a1);
                
        JOptionPane.showMessageDialog(null,"Usuário cadastrado com sucesso!"+txtAluno.getText());
        limpar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    public void limpar(){
        txtAluno.setText() = null;
        txtMatricula.setText() = null;
    }
    
    private void addAluno(Classes.Aluno a1){
        for(int i=0; i<100; i++)
                if(vetor[i] == null){
                    vetor[i] = a1;
                    break;
                }
    }
    private void fTxtMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTxtMensalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTxtMensalidadeActionPerformed

    private void cboxBolsistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxBolsistaActionPerformed
        // TODO add your handling code here:
        if(cboxBolsista.isSelected()){
            fTxtMensalidade.setEnabled(false);
            fTxtDesconto.setEnabled(false);
            fTxtValorFinal.setText("0");
        }
        else{
            fTxtMensalidade.setEnabled(true);
            fTxtDesconto.setEnabled(true);
        }  
    }//GEN-LAST:event_cboxBolsistaActionPerformed

     public void calcularValorFinal(){
        float mensalidade=0, desconto=0, total;
        
        if(fTxtMensalidade.getText().equals(""))
            mensalidade = Float.parseFloat(fTxtMensalidade.getText());
        if(fTxtDesconto.getText().equals(""))
            desconto = Float.parseFloat(fTxtDesconto.getText());
        
        total = mensalidade-desconto;
        
        fTxtValorFinal.setText(String.valueOf(total));
    } 
    
    private void fTxtMensalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTxtMensalidadeFocusLost
        // TODO add your handling code here:
        calcularValorFinal();
    }//GEN-LAST:event_fTxtMensalidadeFocusLost

    private void fTxtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTxtDescontoFocusLost
        // TODO add your handling code here:
        calcularValorFinal();
    }//GEN-LAST:event_fTxtDescontoFocusLost

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        int i;
        int mat = Integer.parseInt(txtMatricula.getText());
        
        for(i=0; i<100; i++){
            if(vetor[i] != null)
                if(vetor[i].getMatricula()==mat){
                    txtAluno.setText(vetor[i].getNome());
                    break;
                }
        }
    }//GEN-LAST:event_btPesquisarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JRadioButton btMatutino;
    private javax.swing.JRadioButton btNoturno;
    private javax.swing.JButton btPesquisar;
    private javax.swing.ButtonGroup btTurno;
    private javax.swing.JRadioButton btVespertino;
    private javax.swing.JComboBox<String> cbCursos;
    private javax.swing.JCheckBox cboxBolsista;
    private javax.swing.JFormattedTextField fTxtDesconto;
    private javax.swing.JFormattedTextField fTxtMensalidade;
    private javax.swing.JFormattedTextField fTxtValorFinal;
    private javax.swing.JList<String> jLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lAluno;
    private javax.swing.JLabel lCurso;
    private javax.swing.JLabel lDesconto;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lIdioma;
    private javax.swing.JLabel lMatrícula;
    private javax.swing.JLabel lMensalidade;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lTurno;
    private javax.swing.JLabel lValorFinal;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JTextArea txtEndereco;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables

}